[project]
name = "motioncore-cht-template"
version = "0.1.0"
description = "Шаблон репозитория для ЧВТ"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "motion-core-API @ ./motion-core-API-0.1.2.tar.gz",
    "motorcortex-python>=0.23.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false
